apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    name: lbl-1
spec:
  replicas: 3
  selector:
    matchLabels:
      name: lbl-1
  template:
    metadata:
      name: testpod
      labels:
        name: lbl-1
    spec:
    containers:
         - name: my-container
           image: nginx:latest
           ports:
             - containerPort: 80
  
