apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    env: test 
spec:
  replicas: 3
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      name: testpod
      labels:
        env: test
    spec:
    containers:
       name: nginx-cntr
       image: nginx:latest
       ports:
        - containerPort: 80
            
