apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    env: dev
spec:
  containers:
   - name: pod1
     image: nginx
     resources:
       limits:
         memory: "128Mi"
         cpu: "500m"
     ports:
       - containerPort: 80
