apiVersion: v1
kind: Pod
metadata:
  name:  podresource
  labels:
    name: dev-lbl
spec:
  containers:
    - name: resource
      image: nginx
      resource:
         requests:
            memory: "64Mi"
            cpu: "100m"
         limit:
             memory: "128Mi"
             cpu: "200m"
             